#dataSource:
#    pooled: true
#    dbCreate: create-drop
#    url: jdbc:h2:mem:devDb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
hibernate:
    hbm2ddl:
        auto: create-drop
    dialect: org.hibernate.dialect.H2Dialect
    cache:
        queries: true
        use_second_level_cache: true
        use_query_cache: false
        region.factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

#Configuraci√≥n para H2
spring:
    datasource:
      driverClassName: org.h2.Driver
      url:   jdbc:h2:mem:devDb
      username: sa
      password: 
    h2:
      console:
        enabled: true
        path: /dbconsole
